name: Lints

on:
  [push,pull_request,workflow_dispatch]

jobs:
  shellcheck:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: >-
            .git
